### ISSUE TITLE
Checking whether the target account follows the source account

### ISSUE THREAD

**Issue by bdashore3** [egg-mode-rs/egg-mode#107]
Hi, I was looking at the docs and wanted to know how to check if the account that mentioned me actually follows me.

I'm currently using the mentions timeline and I understand that gives me a TwitterUser struct. How would I tell if that user is following me?

**Comment by QuietMisdreavus** [comment]
The way you find whether a user follows another user is by using the [`user::relation`](https://docs.rs/egg-mode/0.15.0/egg_mode/user/fn.relation.html) function. You'd pull that info like this:

```rust
let other_user = tweet.user.unwrap();
let relation = egg_mode::user::relation(me.id, other_user.id).await?;

if relation.source.followed_by {
    // add marker saying "Follows you" or the like
}
```

**Comment by bdashore3** [comment]
Thanks for the response! However, what if I wanted to use relation_lookup() since me.id is the authenticated user?

**Comment by QuietMisdreavus** [comment]
If you wanted to use `relation_lookup` instead, it would look something like this:

```rust
use egg_mode::user::Connection::FollowedBy;

let other_user = tweet.user.unwrap();
let lookup = egg_mode::user::relation_lookup(&[other_user.id]).await?;

if lookup[0].connections.contains(&FollowedBy) {
    // add marker saying "Follows you" or the like
}
```

**Comment by bdashore3** [comment]
So, cargo says the function takes 2 arguments and I added the user token in there, but I'm getting this error and I'm not sure why. I tried providing a non-refed u64 and binded the array separate to the function call.

![image](https://user-images.githubusercontent.com/8082010/90069029-a6970200-dcbf-11ea-9688-188413887c12.png)

**Comment by QuietMisdreavus** [comment]
Oh dang, it looks like the `impl From<&u64> for UserID` got removed at some point. Replace the array with something like `[other_user.id].iter().cloned()`, that should make it work. I'll have to add some of the `From` impls back in.

**Comment by bdashore3** [comment]
Yes! That worked! Now for some weird reason, there's this error and I don't know what to make of it

![image](https://user-images.githubusercontent.com/8082010/90075861-6a1dd300-dccc-11ea-9a9f-73ec27129d88.png)

Here's the code
```rust
let other_user = status.user.as_ref().unwrap();
let lookup = relation_lookup([other_user.id].iter().cloned(), &config.token).await?;

if lookup[0].connections.contains(&Connection::FollowedBy) { <- Error occurring on the contains check
      let _ = retweet(status.id, &config.token).await;
      let _ = like(status.id, &config.token).await;
    
      TWEET_MAP.insert(status.id, since_epoch + 3600);
}
```

**Comment by QuietMisdreavus** [comment]
Oh goodness, why did i not throw `PartialEq` on that enum? Since there's no `==` operator for that type, you'll have to use the [`matches!`](https://doc.rust-lang.org/std/macro.matches.html) macro instead:

```rust
let other_user = status.user.as_ref().unwrap();
let lookup = relation_lookup([other_user.id].iter().cloned(), &config.token).await?;

if lookup[0].connections.iter().any(|c| matches!(c, &Connection::FollowedBy)) {
      let _ = retweet(status.id, &config.token).await;
      let _ = like(status.id, &config.token).await;
    
      TWEET_MAP.insert(status.id, since_epoch + 3600);
}
```
