### ISSUE TITLE
Publish release

### ISSUE THREAD

**Issue by RAnders00** [egg-mode-rs/egg-mode#112]
My project is waiting for an egg_mode version compatible with tokio 1.0, given my PR was just merged (#111) could you consider publishing a release to crates.io? Thanks!

**Comment by adwhit** [comment]
I do want this, just need to get round to it

**Comment by bombsimon** [comment]
@adwhit Let us know if you need any assistance, testing or whatever to make this happen! 🍻

**Comment by zackmdavis** [comment]
```TOML
egg-mode = { git = "https://github.com/egg-mode-rs/egg-mode", rev = "6b81073eba9" }
```
is working for me.
