### ISSUE TITLE
Support for Quote Tweeting

### ISSUE THREAD

**Issue by crawfordleeds** [egg-mode-rs/egg-mode#124]
I can't seem to find a way to create a quote tweet. There is retweet of course, but no option to add additional text: https://docs.rs/egg-mode/0.16.0/egg_mode/tweet/fn.retweet.html.

Am I missing something? If not, are there any plans to support quote tweeting or is that something you'd accept as a contribution?

**Comment by tesaguri** [comment]
Quote Tweets are not Retweets and are done with [`POST statuses/update`]'s `attachment_url` parameter. `egg-mode` exposes the interface as [`egg_mode::tweet::DraftTweet.attachment_url`].

[`POST statuses/update`]: <https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/post-statuses-update>
[`egg_mode::tweet::DraftTweet.attachment_url`]: <https://docs.rs/egg-mode/0.16.0/egg_mode/tweet/struct.DraftTweet.html#structfield.attachment_url>

**Comment by crawfordleeds** [comment]
Oh thank you!
