### ISSUE TITLE
PIN authentication not working

### ISSUE THREAD

**Issue by wiseman** [egg-mode-rs/egg-mode#128]
I feel like I must be doing something dumb, but I haven't been able to get PIN-based authentication to work. I'm using egg-mode 0.16.10, and this is my code:

```rust
pub async fn interactively_get_oauth_credentials() -> anyhow::Result<()> {
    let mut line = String::new();
    println!("Enter the bot app's consumer key:");
    std::io::stdin().read_line(&mut line)?;
    let consumer_key = line.trim().to_string();
    println!("Enter the bot app's consumer secret:");
    std::io::stdin().read_line(&mut line)?;
    let consumer_secret = line.trim().to_string();
    println!("consumer key: {:?}", consumer_key);
    println!("consumer secret: {:?}", consumer_secret);
    let con_token = egg_mode::KeyPair::new(consumer_key, consumer_secret);
    // "oob" is needed for PIN-based auth; see docs for `request_token` for more info
    let request_token = egg_mode::auth::request_token(&con_token, "oob").await?;
    let auth_url = egg_mode::auth::authorize_url(&request_token);
    println!("1. Open this URL and get the PIN: {}", auth_url);
    println!("2. Enter the PIN you got from the URL above: ");
    std::io::stdin().read_line(&mut line)?;
    let pin = line.trim().to_string();
    let (token, user_id, screen_name) =
        egg_mode::auth::access_token(con_token, &request_token, pin).await?;
    println!("Authorizing account: {}", screen_name);
    println!("User ID: {}", user_id);
    println!("Token: {:?}", token);
    Ok(())
}
```

When I try it, the `request_token` function returns the following error:
```
Error: Errors returned by Twitter: #32: Could not authenticate you.
```

When I use the exact same consumer key and secret in my node program that uses the [twitter-pin](https://www.npmjs.com/package/twitter-pin) library, it works fine.

**Comment by backspace** [comment]
I’m a Rust newb and therefore don’t have much insight into what’s relevant in the differences in the code you posted but I was able to get PIN-based authentication to work with the example `create_tweet` example script, which relies on [auth code in `examples/common/mod.rs`](https://github.com/egg-mode-rs/egg-mode/blob/8eea554ab9229891114c13254304e3b7c59eb7da/examples/common/mod.rs#L75-L113)

```
Go to the following URL, sign in, and give me the PIN that comes back:
https://api.twitter.com/oauth/authorize?oauth_token=[redacted]
[PIN]

Welcome, FSPSbot, let's get this show on the road!
```

I hope you can figure it out or someone who has more familiarity follows up! 🤞🏻

**Comment by wiseman** [comment]
You inspired me to take another close look, thank you, @backspace. Luckily it was a dumb mistake!  I forgot to `line.clear()` before reading the secret, so I was trying to authorize with a secret that was the consumer key and secret appended together.
