### ISSUE TITLE
migrate repo to github organization

### ISSUE THREAD

**Issue by QuietMisdreavus** [egg-mode-rs/egg-mode#89]
Since it's been a while since i've actively worked on this library, we should probably migrate it to its own organization so that it has its own name instead of just mine on it. We could also solve the "repo name isn't egg-mode" problem at the same time, while we're at it.

I imagine the organization members would just be me and @adwhit to begin with, since we're the current people with push access. I would also like to move the [`egg-mode-text`](https://github.com/QuietMisdreavus/twitter-text-rs) library as well, even though i'm still the only maintainer of that one. I consider it to be "part of egg-mode" even though it's a separate library, so it would be nice for them to live together.

**Comment by adwhit** [comment]
I am fine with doing this. I don't have a huge amount of time to work on this library unfortunately (I had used it at work, which allowed me to spend more time on it, but have since changed jobs), so I would be happy to add other maintainers if anyone volunteers.

**Comment by QuietMisdreavus** [comment]
This is done now! I've moved and renamed both this repo and `egg-mode-text`, and updated the links in this repo. Whenever we publish a new version, the links will be updated there. In the meantime, the existing links should redirect to the new repository just fine.

**Comment by adwhit** [comment]
:+1: That was fast!
